/**:
  ros__parameters:
    distance_threshold: 0.35
    # publish voxelized map pointcloud for debug
    publish_debug_pcd: False

    # use dynamic map loading
    use_dynamic_map_loading: True

    # time interval to check dynamic map loading
    timer_interval_ms: 100

    # distance threshold for dynamic map update
    map_update_distance_threshold: 10.0

    # radius map for dynamic map loading
    map_loader_radius: 150.0
