/**:
  ros__parameters:

    # Latitude of local origin
    latitude: 41.023996553613905

    # Longitude of local origin
    longitude: 28.886452364733607

    # Altitude of local origin
    altitude: 110.00
