/**:
  ros__parameters:
    angular_velocity_offset_x: -0.00030
    angular_velocity_offset_y: 0.00159
    angular_velocity_offset_z: 0.00335
    angular_velocity_stddev_xx: 0.02119
    angular_velocity_stddev_yy: 0.02119
    angular_velocity_stddev_zz: 0.02119
